[tools]
"cargo:diskonaut" = "latest"
"cargo:alphatroya/local_shelf" = "tag:v0.2"
"go:github.com/icholy/git-get" = "latest"
"go:github.com/idursun/jjui/cmd/jjui" = "latest"
"spm:alphatroya/stylus-telegram-bot" = "v1.0"
difftastic = "latest"
go = "latest"
jj = "latest"
lua-language-server = "latest"
neovim = "latest"
rust = "latest"
stylua = "latest"

[settings]
experimental = true
