[tools]
"cargo:diskonaut" = "latest"
"go:github.com/icholy/git-get" = "latest"
difftastic = "latest"
go = "latest"
jj = "latest"
lua-language-server = "latest"
neovim = "latest"
rust = "latest"
stylua = "latest"
opencode = "latest"

[settings]
experimental = true
